version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - internal_network
    deploy:
      resources:
        limits:
          cpus: '0.02'
          memory: 64M
        reservations:
          cpus: '0.01'
          memory: 32M

  celery-worker: # TODO set commands here instead.
    build:
      context: celery_worker
    env_file: .env.celery_example
    volumes:
      - shared-volume:/app/input
    networks:
      - internal_network
    deploy:
      resources:
        limits:
          cpus: '1.50'
          memory: 1000M
        reservations:
          cpus: '1'
          memory: 300M
    depends_on:
      - redis

  flower:
    image: mher/flower
    env_file: .env.celery_example
    ports:
      - "8888:8888"
    networks:
      - internal_network
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 128M
        reservations:
          cpus: '0.02'
          memory: 64M
    depends_on:
      - celery-worker

  fast-api:
    build:
      context: fast_api
    env_file: .env.celery_example
    ports:
      - "8008:8008"
    networks:
      - internal_network
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 64M

    depends_on:
      - celery-worker

volumes:
  shared-volume:
networks:
  internal_network:
