apiVersion: v1
data:
  CELERY_BACKEND_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_IMPORTS: tasks.process_file
  FLOWER_PORT: "8888"
  REDIS_DB: "1"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"CELERY_BACKEND_URL":"redis://redis:6379/0","CELERY_BROKER_URL":"redis://redis:6379/0","CELERY_IMPORTS":"tasks.process_file","FLOWER_PORT":"8888","REDIS_DB":"1","REDIS_HOST":"redis","REDIS_PORT":"6379"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-04-11T01:17:46Z","name":"app-configs","namespace":"fastapi-celery","resourceVersion":"1642","uid":"0b8bd1cd-2807-4ed1-9f29-f458456827f9"}}
  creationTimestamp: "2023-04-11T14:01:57Z"
  name: app-configs
  namespace: fastapi-celery
  resourceVersion: "13868"
  uid: 151bcee2-c54a-4d65-abf0-c98f877276d9