apiVersion: v1
data:
  CELERY_BACKEND_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_IMPORTS: tasks.process_file
  FLOWER_PORT: "8888"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  # Results DB Table
  REDIS_DB: "1"
  # IP Throttling DB Table
  REDIS_DB_IP: "2"
kind: ConfigMap
metadata:
  name: app-configs
#  namespace: fastapi-celery