apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: fastapi-celery

resources:
#  - namespace.yaml TODO namespaces
#  - TODO dynamic configmap
  - configmap.yaml
  - volumes.yaml
  - deployment.yaml
  - ingress.yaml
  - services.yaml
