apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: fastapi-celery

resources:
#  - namespace.yaml TODO namespaces
  - configmap.yaml
  - volumes.yaml
  - base_deployment.yaml
# Run locally. Requires 1 vCPU
  - local_worker_deployment.yaml
# Uploads files to Inference Endpoint VIA Celery worker's threading.
#  - remote_worker_deployment.yaml
# Local testing ingress
#  - local_test_ingress
  - services.yaml
# ReactJS Front End
  - front_end/front_end_deployment.yaml
  - front_end/front_end_service.yaml