apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: fastapi-celery

resources:
#  - namespace.yaml TODO namespaces
  - configmap.yaml
  - volumes.yaml
  - base_deployment.yaml
# Run locally. Requires 1 CPU
  - local_worker_deployment.yaml
# Uploads files to Inference Endpoint VIA Celery worker's threading.
  - remote_worker_deployment.yaml
  - ingress.yaml
  - services.yaml
