apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fast-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: $request_uri

spec:
  rules:
    - host: josh-martin.dev
      http:
        paths:
          - path: /api(/.*|$)
            pathType: Prefix
            backend:
              service:
                name: fast-api-service
                port:
                      name: http
          - path: /docs(/.*|$)
            pathType: Prefix
            backend:
              service:
                name: fast-api-service
                port:
                      name: http
