apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-file-input-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-file-input-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi